### ISSUE TITLE
`datetime.UTC` requires Python 3.11

### ISSUE THREAD

**Issue by weaversam8** [redimp/otterwiki#107]
`datetime.UTC` (which is used in `wiki.py`) [was added in Python 3.11](https://docs.python.org/3/library/datetime.html#datetime.UTC), but `pyproject.toml` only requires Python 3.7 or greater:

https://github.com/redimp/otterwiki/blob/c805922fe886f724eefdd118ac0c1d444d59c8aa/otterwiki/wiki.py#L41

https://github.com/redimp/otterwiki/blob/c805922fe886f724eefdd118ac0c1d444d59c8aa/pyproject.toml#L9

Do you want to update the minimum Python version, or try to find a workaround?

**Comment by redimp** [comment]
Lazy me, I forgot to bump up the requiremnts. I've caught up on it. Thank you!
