### ISSUE TITLE
Error: INSTALLATION FAILED: manifest does not contain minimum number of descriptors (2), descriptors found: 1

### ISSUE THREAD

**Issue by baldy-cape** [redimp/otterwiki#122]
Following Installation page examples, installing with helm, get the error ```INSTALLATION FAILED: manifest does not contain minimum number of descriptors (2), descriptors found: 1```

```
$ helm install my-otterwiki \
  --set config.SITE_DESCRIPTION="An Otter Wiki deployed with Helm" \
  --set ingress.enabled=true \
  --set ingress.hosts[0].host="helm.otterwiki.com" \
  oci://registry-1.docker.io/redimp/otterwiki
Error: INSTALLATION FAILED: manifest does not contain minimum number of descriptors (2), descriptors found: 1
```

As a work around adding, ```--version 0.1.0``` allows installation. 
```
$ helm install my-otterwiki \
  --set config.SITE_DESCRIPTION="An Otter Wiki deployed with Helm" \
  --set ingress.enabled=true \
  --set ingress.hosts[0].host="helm.otterwiki.com" \
  oci://registry-1.docker.io/redimp/otterwiki \ 
  --version 0.1.0
Pulled: registry-1.docker.io/redimp/otterwiki:0.1.0
Digest: sha256:01dc6e6625055a35899bb9d30cb038c34d8dade51b6ff2855f1b52f9e5718895
NAME: my-otterwiki
LAST DEPLOYED: Thu Jul  4 10:37:43 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
Open up your installation of An Otter Wiki via
```

Tested with Helm 3.11
```
$ helm version
version.BuildInfo{Version:"v3.11", GitCommit:"", GitTreeState:"", GoVersion:"go1.21.6"}
```

**Comment by redimp** [comment]
Hey @baldy-cape, thank you for digging into this. 

I reproduced the error and your solution. Will update the documentation and add the `--version 0.1.0` argument.

I'm not thrilled with the solution, but it's good enough for now. My expectation of helm was that it would also be able to filter a mixed repository and find the latest version of the chart. Unfortunately that was pure wishful thinking.

**Comment by redimp** [comment]
I have to think about this. Maybe I should put some extra effort into this and set up a chartmuseum e.g. `charts.otterwiki.com`.
