### ISSUE TITLE
rearranging page after closing sidebar when selecting header on mobile

### ISSUE THREAD

**Issue by shangri26199** [redimp/otterwiki#124]
when i am inside the document and open sidebar, the main text of document were shrinked, so, when i select header in sidebar, its navigate correctly, but when i close a sidebar, the content again grows horizontaly, losing headers position(because number of rows is changing)

**Comment by redimp** [comment]
I see the problem .. Hm, will check if displaying the sidebar not expanding but as overlay (on small devices) solves this problem.
