### ISSUE TITLE
Request a convenient way to add wikilink

### ISSUE THREAD

**Issue by yuukarii** [redimp/otterwiki#128]
Hi,
I usually use wikilinks to connect between pages. I wish there was a button to help me add a wikilink, displaying a list of existing pages. I have many subpages, and it's difficult to remember the names of the parent and the page I want to link to.

Thanks!

**Comment by redimp** [comment]
Hey @yuukarii, thanks for opening up this request. Maybe the link button should open up a modal which lets you choose from/search in the list of existing pages? Maybe this would be useful for attachments, too?

**Comment by yuukarii** [comment]
Hi @redimp , yes, that's exactly what I want.

**Comment by redimp** [comment]
Finally working on this. I've decided to rework the right sidebar in the editor. Quick preview: 
![image](https://github.com/user-attachments/assets/7f9174af-2353-428e-bacf-5ed37157d104)
