### ISSUE TITLE
Error when starting docker container on windows

### ISSUE THREAD

**Issue by marcrleonard** [redimp/otterwiki#13]
When following the readme to deploy to docker, the docker container stops with this error:

`otterwiki-web-1 | /usr/bin/env: ‘bash\r’: No such file or directory`

... I suspect it has to do with the `#! /usr/bin/env bash` at the top of docker-entrypoint.sh on windows.

**Comment by redimp** [comment]
The shebang is fixed in 2a70c40, i have to find a windows to test that.

**Comment by marcrleonard** [comment]
I seem to be getting the same error. Does this script get executed within the container or prior to?

**Comment by redimp** [comment]
The script is executed in the container.

What confuses me is that looks like an error in line endings, like the file is checked out with windows line endings which breaks in the container.

Can you try to configure your git to use `\n` line endings with

`git config core.autocrlf false`

**Comment by redimp** [comment]
On that note: I will build and release Docker images on the weekend. I will ping you that you can try it. I guess the building in Windows doesn't work as intended. Sorry for that, I never tried it.

**Comment by marcrleonard** [comment]
I did both `git config core.autocrlf false` and `git config core.autocrlf input` deleted the image and it worked! Thank you!
