### ISSUE TITLE
Splitting Otterwiki Docker setup into multiple containers?

### ISSUE THREAD

**Issue by mattock** [redimp/otterwiki#142]
I heavily modified the Otterwiki Docker / Docker Compose setup for my own production use. Basically the setup now consists of three containers instead of just one:

* web (uwsgi)
* nginx
* db (postgres)

This meant that supervisord was no longer required/desired, so I ripped that one out as well. The end result is probably not general-purpose enough to include as-is in this project.

That said, would you be open to including this type of Docker setup in the Otterwiki Git repository? It could probably live side-by-side with the old Docker setup without too much fuzz. Most of the code repetition would be in the Dockerfile.

**Comment by redimp** [comment]
Hey @mattock, first of all thank you for the work and thoughts you bring to this project!

A first step in this direction has been done, there is the [docker/Dockerfile.slim](https://github.com/redimp/otterwiki/blob/main/docker/Dockerfile.slim) whis is running only the `uwsgi` is running, serving both the app and the static files, rendering `nginx` unnecessary and therefore `supervisord`.

This is not documented yet, but I'll make up for it as soon as possible. An example `docker-compose.yaml` for a complex setup like the one you proposed would be useful. Contributiuons are welcome!

**Comment by mattock** [comment]
> Hey @mattock, first of all thank you for the work and thoughts you bring to this project!

Some backstory: I looked into a gazillion of different wikis and after getting very frustrated with our "prime candidates" (xwiki and wiki.js) I had a pause. Then, by accident, I found Otterwiki which looked very promising. In fact, I added Otterwiki to the Wikipedia's "List of wikis" article so that others might more easily find it.

Otterwiki seems to do what we at the OpenVPN project needs and I always try to contribute back whenever possible. So I'm glad if I can be of assistance!

> A first step in this direction has been done, there is the [docker/Dockerfile.slim](https://github.com/redimp/otterwiki/blob/main/docker/Dockerfile.slim) whis is running only the `uwsgi` is running, serving both the app and the static files, rendering `nginx` unnecessary and therefore `supervisord`.
> 
> The `redimp/otterwiki(version)-slim` image is beeing released along the `redimp/otterwiki(version)` image on [hub.docker.com](https://hub.docker.com/repository/docker/redimp/otterwiki/tags?name=-slim).
> 
Noted.

> This is not documented yet, but I'll make up for it as soon as possible. An example `docker-compose.yaml` for a complex setup like the one you proposed would be useful. Contributiuons are welcome!

I'll try to make my "production" setup as non-invasive as possible, so that it could potentially be merged. It already works fine afaics. I will see how to minimize divergences between it and the existing development Docker setups so that I can send a reasonable PR your way.

**Comment by redimp** [comment]
I've added the documentation how to make use of the `-slim` image variant to the [Installation Documentation](https://otterwiki.com/Installation#the-slim-image-variant). Thank you @mattock for bringing this up!

**Comment by mattock** [comment]
Thanks! I'll check out the -slim variant once I get back to Otterwiki setup again. I may come up with some follow-up PRs.
