### ISSUE TITLE
Use bjoern instead of uwsgi for lower resource usage

### ISSUE THREAD

**Issue by neuhaus** [redimp/otterwiki#145]
Since Otterwiki targets small installs, have you considered using [bjoern ](https://github.com/jonashaag/bjoern)instead of uwsgi?
It should be fast and need less RAM.

**Comment by redimp** [comment]
Hey @neuhaus! Thanks for suggesting bjoern, never heard of it before.

Currently I'm considering to remove nginx (and rendered unnecessary supervisord) from the image. This is discussed in #121.

The `otterwiki:2.x.y-slim` images works in this way, see [Dockerfile.slim](https://github.com/redimp/otterwiki/blob/main/docker/Dockerfile.slim) for the details.

Without nginx, the WSGI server used must be able to serve static files efficiently, which uwsgi can do amazingly well according to my benchmarks. This feature is not supported by bjoern, as far as I have seen. Serving the static files via Flask is unfortunately far too inefficient to be considered.

**Comment by neuhaus** [comment]
Another solution would be to provide all static files in a volume so nginx can serve them, even when it's not in the container.
Most users will probably need nginx in order to provide more than one service per virtual host.
