### ISSUE TITLE
Add support for ACLs

### ISSUE THREAD

**Issue by tionis** [redimp/otterwiki#147]
Support for ACLs would be great, even simple ones like `user -> group -> regex` would work great for many use cases.

**Comment by redimp** [comment]
Hey @tionis, thank you for this request. You are not alone with this: In #54 was proposed for handling permissions and 

This is on my medium list of features to be added to An Otter Wiki. Will bump it up!

**Comment by tionis** [comment]
Oh, I totally overlooked that! Seems I used the wrong keywords while searching.
Nice to hear that is somewhere on the list, I'm also happy to brainstorm ideas for the permission system if needed.
