### ISSUE TITLE
Allow direct renaming of folders

### ISSUE THREAD

**Issue by freezingDaniel** [redimp/otterwiki#149]
I hope I have not just overlooked a way to do this correctly, but I could not find a simple way to rename a folder

say one creates 2 wiki entries:

a/b
a/c
but not a itself

Filestructure:
```txt
└── a
    ├── b.md
    └── c.md
```

to rename the folder a, the wikis b and c need to be moved. This can be tedious for many pages.

It would be desirable that the "rename" option exists on a / empty dirs / the "Page Index" too and not only for wiki entries (md).

**Comment by redimp** [comment]
Hey @freezingDaniel, thanks for bringing this to my attention .. a page that only exists as pageindex lacks `Rename` and `Delete` .. currently I'm not sure if an `Edit` button should be available too.

**Comment by freezingDaniel** [comment]
By `Edit` you mean a shortcut to create the respective md-file?
Then maybe, but I'd say as a separate Issue with lower priority, as I found the "workaround" of just using the regular "Create Page" quite easily.

- Edit/Create page: Possible to find (first guess)
- Delete: bit harder to think of creating a page first
- Rename: would be really nice as pages can't be deleted separately and the workaround is tedious.

But as food for thought, a possible implementation might include:
- Create an md-file for each folder (and keep the names synced)
- Interpret an empty md-file as pageindex :)

**Comment by redimp** [comment]
Hehe, just creating empty `.md` files and treating them as pageindex is a idea. Will think about it!

Another feature in this context I was thinking about, was to add a pageindex to a page/a page to a pageindex. The first. idea was to make this via yaml front matter, like

```markdown
---
pageindex: top / bottom / hidden (default)
---
# The Page

and its content.
```
