### ISSUE TITLE
Pushing to the git server requires `Admin` privileges

### ISSUE THREAD

**Issue by Richardk2n** [redimp/otterwiki#154]
I can clone and edit locally, however when I upload, I get a 403 error with my user having all privileges except `Admin`.
If I push using my root user it works.

For force pushing Admin should probably be required.
Otherwise, I would have expected upload to be sufficient.

**Comment by redimp** [comment]
Bug confirmend. Reproduced it in the latest version. Will look into it asap. The ATTACHMENT/UPLOAD permission should users enable to push to the wiki.

**Comment by redimp** [comment]
Fix released in [v2.7.0](https://github.com/redimp/otterwiki/releases/tag/v2.7.0).
