### ISSUE TITLE
Starts manually okay, but as service 'Error: Please configure a random SECRET_KEY'

### ISSUE THREAD

**Issue by nateProjects** [redimp/otterwiki#157]
Hi, hope you can help - it's probably something simple I'm missing.

This works perfectly from the command line -

`/var/www/otterwiki/venv/bin/uwsgi --http 127.0.0.1:8080 --enable-threads --die-on-term -w otterwiki.server:app`

But when it is run from the service it errors -

```
Error: Please configure a random SECRET_KEY with a length of at least 16 characters.
otterwiki.service: Main process exited, code=exited, status=1/FAILURE
otterbox systemd[1]: otterwiki.service: Failed with result 'exit-code'.
```

Relevant part of - /etc/systemd/system/otterwiki.service -

```
[Service]
User=www-data
Group=www-data
WorkingDirectory=/var/www/otterwiki
ExecStart=/var/www/otterwiki/venv/bin/uwsgi --http 127.0.0.1:8080 --master --enable-threads --die-on-term -w otterwiki.server:app
SyslogIdentifier=otterwiki
```

setting.cfg definitely has a working SECRET_Key too.

Any help would be appreciated

**Comment by redimp** [comment]
Hey @nateProjects, thank you for reporting this! The documentation was missing an important setting:
```
[Service]
...
Environment=OTTERWIKI_SETTINGS=/path/to/the/settings.cfg
...
```
I've just updated this on <https://otterwiki.com/Installation> and added a comment about changing the `--http` option if necessary.

**Comment by nateProjects** [comment]
> Hey @nateProjects, thank you for reporting this! The documentation was missing an important setting:
> 
> ```
> [Service]
> ...
> Environment=OTTERWIKI_SETTINGS=/path/to/the/settings.cfg
> ...
> ```
> 
> I've just updated this on https://otterwiki.com/Installation and added a comment about changing the `--http` option if necessary.

That's it! Perfect! Thanks
