### ISSUE TITLE
Copy code block function not working

### ISSUE THREAD

**Issue by tvmp** [redimp/otterwiki#159]
Hello and thank you for the amazing Wiki!

I am running it in docker compose and everything is working great apart from the copy code block function.
Even though I can copy code from the sample pages i.e. [here](https://otterwiki.com/Examples/All%20Syntax%20Features#code-blocks) or [here](https://otterwiki.com/Examples/Syntax%20Highlighting), the icon that provides the copy function in my instance is not copying the content of a code block to the clipboard.

I am only using otterwiki locally within my LAN, if that makes any difference.
Have I ommitted something?

**Comment by redimp** [comment]
Hey @tvmp, no idea yet what might go wrong. With the sample pages working we can rule out that your browser or the javascript is not working at all, but for the sake of completeness two questions:
- Which browser are you using?
- Is there an error message in the browsers console? (open via <kbd>F12</kbd> in Firefox or Chrome

**Comment by tvmp** [comment]
Tried with latest Firefox and latest Chrome, no luck in either, even though the same browsers work fine with the sample links above.

F12 in Firefox produced the error below:

Uncaught TypeError: navigator.clipboard is undefined

No idea what that means though!

**Comment by tvmp** [comment]
I think it won't work otherwise, it needs to be https, not otterwiki's fault so I am closing this.
Thanks again!
