### ISSUE TITLE
Configure Application Preferences via Web Interface

### ISSUE THREAD

**Issue by redimp** [redimp/otterwiki#16]
A feature to (optional) configure the wiki via a web interface is on tis way:

![image](https://user-images.githubusercontent.com/112056/193282799-abca979f-d879-435b-b33b-0ea237dbd7cf.png)

**Comment by marcrleonard** [comment]
yesss amazing!

**Comment by redimp** [comment]
Done in 525c26d174233d98873430450fce07e21cb5c7a1
