### ISSUE TITLE
`Using docker compose` example on production website has spelling error in property

### ISSUE THREAD

**Issue by kyle-mckay** [redimp/otterwiki#161]
Hello,

I was using the docker compose example on [Using docker compose](https://otterwiki.com/Installation#using-docker-compose) from the website, and there is an alternative configuration that uses environment variables to declare the mail server settings. I noticed that while attempting to configure it, that `environment` is spelled `environemnt` in your example compose.

![image](https://github.com/user-attachments/assets/cdfd2177-841b-41e0-a9a8-af757f140f9d)

I am not sure if this is an appropriate place to submit an issue regarding the official website, however as I didn't see any direct dependencies in the repository itself that lines up with the production site, I figured this is the next best place to mention it.

**Comment by redimp** [comment]
Hey @kyle-mckay thank you for reporting this, this was the right place! I fixed the typo.
