### ISSUE TITLE
Relative image/attachement links

### ISSUE THREAD

**Issue by Kilidsch** [redimp/otterwiki#163]
Hey,

Otterwiki seems like a great project and we want to switch to it from our old wiki.  
During the switch I noticed something:

In the preview, relative links to images worked, i.e. if I upload an image as an attachement for a page and add a relative image-link, the image is displayed correctly. On the finished page, the image is not displayed. To be displayed on the finished page, an absolute link is required.

So the question: Are relative links to attachements supposed to work?

**Comment by Kilidsch** [comment]
Ok, after thinking about it a bit here is what I think happens:

Otterwiki just pastes the link form the image link into an image tag. So we get

```
<img src="relative-path.jpg" />
```

This assumes it is in the same directory, so if this is on page `www.my-otterwiki.com/chapter/page` it tries to load `www.my-otterwiki.com/chapter/relative-path.jpg`. When editing, the link changes to `www.my-otterwiki.com/chapter/page/edit`, which leads the relative `img`-tag to search in `www.my-otterwiki.com/chapter/page`; which is coincidentally correct.

This probably means it is not supposed to work in either. And while a relative link `pagename/relative-path.jpg` would work, it would break in preview. So relative paths are just not supported properly.

**Comment by redimp** [comment]
Hey @Kilidsch, thank you for bringing this up.

It would be nice to be able to reference attachments not with the full path,

e.g.
```markdown
![](/Example/a/example.png)
```

but relative:
```markdown
![](example.png)
```
or
```markdown
![](./example.png)
```

Currently the renderer knows nothing about the path of the page it's rendering, will have to look into it to find a nice solution.
