### ISSUE TITLE
Layout Ideas

### ISSUE THREAD

**Issue by marcrleonard** [redimp/otterwiki#18]
I feel like given the way some of these types of apps function there are a few design patterns that could be used. Here are some ideas:

- The left side nav could be a user defined set of pages (maybe there is a default as well) ... Basically, a set of pages that are 'most important' to the user.
- When in the page view mode, have it be broken into two columns. The left would be the page, and the right would be the table of contents nav. I also moved the edit button into this 'sticky' column. I think it makes more sense to have the edit button encapsulated inside the page rather than part of the nav. See 1st screenshot. (sidenote: this same principal could be applied to the save/preview buttons when in edit view)
- Since the Markdown Syntax Guide only applies when editing a document, have it be a reference tab at the bottom. See 2nd/3rd screenshot.

<img width="1414" alt="Screen Shot 2022-10-01 at 6 28 32 AM" src="https://user-images.githubusercontent.com/24658895/193409665-23a9e938-2379-4113-8f0b-f65a0dbc5768.png">

<img width="1335" alt="Screen Shot 2022-09-30 at 8 18 39 PM" src="https://user-images.githubusercontent.com/24658895/193379926-8e719a46-959e-4080-a585-c3cbb65e803c.png">

<img width="1337" alt="Screen Shot 2022-09-30 at 8 19 07 PM" src="https://user-images.githubusercontent.com/24658895/193379935-89625113-52ac-4197-8d7e-f14bdbf35fc3.png">

Let me know how you like these changes and I will issue a PR

**Comment by marcrleonard** [comment]
Maybe I've taken it a step too far, but I'm finding it a slight pain point to access attachments of a page. Maybe this could be a first class citizen of the page view (like TOC). See screenshot

<img width="1447" alt="Screen Shot 2022-10-02 at 7 41 28 AM" src="https://user-images.githubusercontent.com/24658895/193457216-de4b33d1-01f0-4eaf-b2d4-3670d5ab3006.png">

**Comment by redimp** [comment]
1.) User defined set of pages in the sidebar

I like this idea, currently the sidebar is too empty. To clarify: Do you want a) an admin to be able to  would suggest to let either an admin choose which links should be placed there or b) each user can pick their own favored wiki pages?

2.) Adding additional columns

Multiple wikis do these, I'm not a very big fan of that -- maybe because I never use a wiki on full screen ... I would not oppose a change like this if alle the information will still be available on smaller screens without strechting the content too far.

3.) Markdown Syntax Guide under the editor

This is a fantastic idea. I would really like to have this feature.

**Comment by marcrleonard** [comment]
> 1.) User defined set of pages in the sidebar
> 
> I like this idea, currently the sidebar is too empty. To clarify: Do you want a) an admin to be able to would suggest to let either an admin choose which links should be placed there or b) each user can pick their own favored wiki pages?

Hmm... Well... I guess I'm not sure yet. Maybe as an incremental improvement it could display a contextually relevant TOC for the give page you are viewing. So like... The sidebar will show all sibling page (at the same level) + maybe 1-2 levels of it's h1/h2 anchors For each page. I can clarify if this is confusing.

> 2.) Adding additional columns
> 
> Multiple wikis do these, I'm not a very big fan of that -- maybe because I never use a wiki on full screen ... I would not oppose a change like this if alle the information will still be available on smaller screens without stretching the content too far.

Yeah fair enough. That totally makes sense. Maybe that sidebar will just hide on a smaller screen? The bootstrap/halfmoon classes will do this automatically. 

> 3.) Markdown Syntax Guide under the editor
> 
> This is a fantastic idea. I would really like to have this feature.

Awesome! Question - I cant figure out the css class to specify a light/dark mode aware background color. What is it?

Thanks for the feedback! I'll wrap 2 and 3 into a PR.

**Comment by redimp** [comment]
> Awesome! Question - I cant figure out the css class to specify a light/dark mode aware background color. What is it?

The dark-mode toggle in the gethalfmoon framework add the class "dark-mode" to the `<body>` and as far as I unterstood (I'm not a CSS, not even an UI guy) everything inherits this. I've used it e.g. to change the layout of the `<pre>` and `<code>` tags:

First the layout stuf is define for `.code`:

https://github.com/redimp/otterwiki/blob/98ec1d8646f5b28b1b374b4f5d43b4b6cd8747f6/otterwiki/static/css/otterwiki.css#L69

When dark mode is enable the `.dark-mode .code` comes **on top** (and changes only the background color):

https://github.com/redimp/otterwiki/blob/98ec1d8646f5b28b1b374b4f5d43b4b6cd8747f6/otterwiki/static/css/otterwiki.css#L79

**Comment by marcrleonard** [comment]
Awesome. Thanks for those samples. I am still having a hell of a time getting the light/dark modes to work for the markdown syntax reference box. I suspect I need to better utilize one of their canned classes (like .card)

**Comment by marcrleonard** [comment]
Finally got it working. Pull request here: https://github.com/redimp/otterwiki/pull/22

**Comment by redimp** [comment]
I looked into the pull request and I like the changes! Well done. 

Page View: The right sidebar with the table of contents and the attachments is nice!

Editor: The Markdown Syntax looks nice! The Attachment list on the right, with the copy button is a great idea.

I would like to tweak a few things, will look into it tomorrow:

1.) with a small (x-axis) browser there is still the sidebar on the left, but the sidebar on the right is already hidden, so that there is no table of contents at all. I would like to letthe TOC appear on the left, in that case.

2.) Page View: The "Edit Page" Button on the sidebar on the left is imho too dominant (and the small button in the upper right very close to it, that looks like an unecessary duplication.

3.) Editor: I'm thinking about the large "Edit Attachment" Button, even more than the "Edit Page" Button it dominates the right side, where the more important buttons Save/Preview/Cancel are much smaller.

Thanks for the work, I apprecicate that!

**Comment by marcrleonard** [comment]
> 1.) with a small (x-axis) browser there is still the sidebar on the left, but the sidebar on the right is already hidden, so that there is no table of contents at all. I would like to letthe TOC appear on the left, in that case.

Oh thats a good point. Another option would be to have a little tab-like button on the right to access that TOC column when the right column is collapsed (it would fly out overtop or something)

> 2.) Page View: The "Edit Page" Button on the sidebar on the left is imho too dominant (and the small button in the upper right very close to it, that looks like an unecessary duplication.

Yeah it is redundant.

> 3.) Editor: I'm thinking about the large "Edit Attachment" Button, even more than the "Edit Page" Button it dominates the right side, where the more important buttons Save/Preview/Cancel are much smaller.

The "Edit Attachments" button could be a simple link, something like this:

<img width="397" alt="Screen Shot 2022-10-05 at 6 19 19 AM" src="https://user-images.githubusercontent.com/24658895/194058775-fb7d7f57-0352-4584-bca8-6ddd02593245.png">


I was thinking about this new sidebar I added and boiled down why it could be helpful and may be able to inform a future design
- I noticed that both "nav bars" (left and top) were both very dynamic. Depending on what view you were in, the contents changed. 
- For some reason, this was making brain work a little hard to figure out how to get around as typical nav bars contain more high-level options - less contextual to the page you're on.
- By adding the right-hand column, that would provide the "localize" contextual information for the given view you were in (edit/view)

Given what I wrote above, I don't think I got the design perfect in my PR, but maybe this helps better convey what I was noodling on 😊

**Comment by redimp** [comment]
After looking through your code and getting fond of the idea of an extra sidebar, I spent some time and tried to solve the right-hand-bar in the "gethalfmoon-way".

![resize-x](https://user-images.githubusercontent.com/112056/194217101-94178bfa-7421-4216-88b9-c2b690e05e13.gif)

You find my approach in the branch [feature-extra-nav](https://github.com/redimp/otterwiki/tree/feature-extra-nav).

I will cherry pick the features you've implemented on the weekend (if you aren't faster ;) ):

- Attachments on the page view
- Attachment in the editor
- Markdown Syntax Popup

**Comment by redimp** [comment]
I reworked how the attachments are displayed in the sidebar, see [feature-extra-nav](https://github.com/redimp/otterwiki/tree/feature-extra-nav). Will merge this into the main branch tomorrow.

But I'm still struggeling with the Markdown Syntax popup.

**Comment by marcrleonard** [comment]
Awesome! I'll have a look!

**Comment by redimp** [comment]
Continued the work on the right sidebar, I guess this is ready to be merged. Will push the branch tomorrow. 

Worked on the markdown help Popup and found a solution that fits right in. Will push that tomorrow, too.

**Comment by redimp** [comment]
After testing the feature-extra-nav for a few days, I must say, I like it. What to put in the exra-nav on the right is another discussion.

The attachments on the normal page view are more a distraction then useful:

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/112056/198365336-8a2ebada-f17c-4326-b572-8cfa8731f472.png">
 
If you want to make them useful, you have to name the properly. But, when you write a page, and copy and paste an image into it, it will be ranmed randomly, but the link in markdown is already alright, so you have to rename the image and then re-edit the page.

**Comment by redimp** [comment]
Markdown Help Popup added in: 5517bfa
extra-nav-bar added for xl screens in: 210e1bf
