### ISSUE TITLE
Initial default homepage (in place of 404)

### ISSUE THREAD

**Issue by marcrleonard** [redimp/otterwiki#19]
To make the initial app empty app a bit more 'friendly' I think rather than displaying the 404 (which, is quite nice actually), there should be a boilerplate home page. Maybe it can incorporate a bit of the markup guide + an edit button. Just an idea! Feel free to reject it.

**Comment by redimp** [comment]
The feature was added in 2c16afa.

The `initial_home.md` needs some improvement though.

**Comment by redimp** [comment]
With the improvements in

- 29d7a48357535f646e25e97af9b55818082ea3da
- 8742f665163abf87e3080c41929b48af28e0d804

fine for now.
