### ISSUE TITLE
Otter Wiki cannot be "a software" because "software" is an uncountable noun

### ISSUE THREAD

**Issue by rnkn** [redimp/otterwiki#23]
Hello!

No bugs to report, just a friendly heads up that the word "software" is an uncountable noun, so there cannot be "a software" or several "softwares". Correct wording would be:

> An Otter Wiki is Python-based software for collaborative content management, called a wiki.

**Comment by redimp** [comment]
github about section and Readme fixed in [399a6a3](https://github.com/redimp/otterwiki/commit/399a6a348026022b515d7c7b963b8b6e3d941581).

Thanks!
