### ISSUE TITLE
Global TOC

### ISSUE THREAD

**Issue by marcrleonard** [redimp/otterwiki#31]
As I've been using the wiki, I'm still finding it a bit tricky to get around. There is the alphabetized listing of articles, which is helpful, but I wonder if something more akin to a Table of Contents page would be helpful. This would traverse the created pages (including sub folders) and come up with a hierarchical view. 

I have a prototype for this, it includes looking in sub directories and specifying depth. This page would have a slight leg up on the A-Z view, as once sub folder are in and the user starts organizing the wiki, that organization would be clear to see in this view. I will push a PR for you to look at.

**Comment by marcrleonard** [comment]
PR submitted here: https://github.com/redimp/otterwiki/pull/33

**Comment by redimp** [comment]
I like the idea of a global TOC. To make it a complete feature it should include all the headlines of the pages (and link to them).

**Comment by marcrleonard** [comment]
I did consider this (since there is already a mechanism to do get the page toc, which could be utilized), but didn't implement it for two reasons:

1. It could quickly become a pretty heavy weight operation (opening/parsing every file on disk)
2. It didn't seem to fit with the 'scope' of what the global TOC would provide. It's a high-level overview of the structure of the wiki (again, this would make more sense with sub directories).

Thoughts?

**Comment by redimp** [comment]
I’m on the road, so only a quick answer. 

2. My understanding was that a toc should be more complete then just a page index. Both must be able to deal with subdirectories (at least optional). 

1. I agree, this might be a more heavy disk operation. But for getting more than the Page Index out of it, it might be worth the price. (Or a user willing to pay in the waiting time.) In comparison, a search would take the exact same disk lifting. 

I would like to give this a shot, will do this later today.

**Comment by marcrleonard** [comment]
Yes true! It is the same as search!

**Comment by redimp** [comment]
I finished the global toc, including the headers of the pages, please check the [feature-global-toc](https://github.com/redimp/otterwiki/tree/feature-global-toc) if this is useful and works as intended. 

Preview:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/112056/196059246-7da49489-14f2-476a-99e7-3145222ce649.png">

**Comment by redimp** [comment]
Will work on this later today (have to check if the subdirectories work as intended.

**Comment by redimp** [comment]
PageIndex has the feature of displaying the headers:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/112056/198882430-801e255d-121e-4845-8c15-879b62c7a415.png">
