### ISSUE TITLE
Add 'warning' for pages not under version control (rather than 404)

### ISSUE THREAD

**Issue by marcrleonard** [redimp/otterwiki#32]
I ran into an interesting situation. I was moved some .md files from an old repo into my current dev repo, and when trying to navigate to the page I was confronted with a 404. I chased it down the debugger and realized it's because it had not been added under version control (which makes sense why it would fail). Since it was able to load the page just fine from the filesystem (before it raised an exception from git), I was thinking we could add a warning like this:

<img width="1169" alt="Screen Shot 2022-10-14 at 7 21 32 PM" src="https://user-images.githubusercontent.com/24658895/195962856-c7bcee3f-4f20-4ff6-af6b-401e3b262f3d.png">

Let me know what you think! Happy to submit a PR! I could see this being a useful feature if you are haphazardly throwing .md files in your repo folder.

**Comment by redimp** [comment]
I like this idea. I don't think it would be a typical usecase, but at least for me it would be very useful.

**Comment by marcrleonard** [comment]
PR here https://github.com/redimp/otterwiki/pull/34

**Comment by redimp** [comment]
Merged
