### ISSUE TITLE
scharfes s sz ß at beginning of word in title breaks links in A-Z

### ISSUE THREAD

**Issue by zmberber** [redimp/otterwiki#45]
when the `ß` character is in the middle of a word in a title (e.g. `straße`), everything is fine, however, when it is in the beginning of a word of a title, (e.g. `ßuper ding`, `tolle ßau`), the links in the "A-Z" page capitalize it and convert it to an "Ss" (e.g. `Ssuper Ding`, `Tolle Ssau`), which breaks the link.

typing in the link by hand works of course.

what is the use case?  well, it is not too important, but sometimes it is practical to clump batches of articles together in seperate "categories", so that the "A-Z" page doesn't clutter up, for example "Meeting 2022-11-14" and so on.  this is done by using a special symbol at the beginning so that they get sorted after all of the letters.  so the titles would be "ß Meeting 2022-11-14" and so on.

this is not very important, we found other special characters like the euro symbol etc, but this is how we found this glitch.

**Comment by redimp** [comment]
Bug confirmed. Will look into it.
