### ISSUE TITLE
links in tables do not properly interpret line charecter

### ISSUE THREAD

**Issue by EXOgreen** [redimp/otterwiki#50]
Markdown

```
| name | date | link |
| -------- | -------- | -------- |
| John | 01/31/1996 | [[people/John]] |
| Mary |10/08/2001 | [[Mary|people/Mary]] |
```

Expected

![image](https://github.com/redimp/otterwiki/assets/7752505/21f26153-23f5-4849-9147-8993aa2f3b3d)

Actual result

![image](https://github.com/redimp/otterwiki/assets/7752505/5693a0ab-337a-429f-8f54-17e450c4a7d2)

**Comment by redimp** [comment]
Confirm this bug. Thx for reporting this! Have to dig into mistune to fix that.

Fortunately the markdown link work as expected, maybe this workaround helps you:

```
| name     | date      | link                |
| -------- | --------- | ------------------- |
| Mary     |10/08/2001 | [Mary](people/Mary) |
```
