### ISSUE TITLE
Javascript escaping is turned off

### ISSUE THREAD

**Issue by cueball23** [redimp/otterwiki#51]
If you write <script>alert(1)</script> on a site in the wiki it doesn't get escaped. And is executed on viewing of the page. 
I expected it to get escaped or at least the site content loaded into a sandboxed iframe.

Is escape=False really necessary for the function of the wiki?

https://github.com/redimp/otterwiki/blob/f238b68e7e9692925c64565609f999081bd04576/otterwiki/renderer.py#L155C7-L155C7

**Comment by redimp** [comment]
Thx for reaching out!

There is indeed room for improvement here. The idea in not escaping html was to enable editors to paste html into the wiki, e.g. complicated tables or markup that is not in markdown.

This is a feature I don't want to remove. But of course adding potentially malicious (or at least anoying) javascript should be prevented.

Would sanitizing be a good trade-off? With a sanitizer that allows safe html tags and escapes all others? Might even be useful to check if all the tags are closed.

**Comment by redimp** [comment]
I want a clean (no pun intended) solutuin. Will check html-sanitizer and [bleach](https://bleach.readthedocs.io/en/latest/index.html) later today.

**Comment by redimp** [comment]
Bleach is now used in the renderer. It is not possible to inject javascript into wiki pages via `<script>` any event like `onmouseover=` or `onclick=` anymore.

Checkout either `:latest` or at least [2.0.0-beta24](https://hub.docker.com/layers/redimp/otterwiki/2.0.0-beta24/images/sha256-d80bd710592d2ea00275a37bb342e27377d9c55145dc3df5e8a02e4cacd44130?context=repo)
