### ISSUE TITLE
Space in article name breaks new url schema.

### ISSUE THREAD

**Issue by cueball23** [redimp/otterwiki#52]
In [v2.0.0-beta24](https://github.com/redimp/otterwiki/releases/tag/v2.0.0-beta24) internal Wiki Links are converted to the 
```
[Article Name}(/Article Name)
```
schema.

If the article name has a space in it the schema is broken. I think a valid approach would be to replace a space in the URL with "%20".

https://github.com/redimp/otterwiki/blob/c071d9dc4a565f567e9c04aefb5c174949ae848f/otterwiki/renderer.py#L84C28-L84C28

**Comment by redimp** [comment]
This is fixed in `:latest` or at least [v2.0.0-beta26](https://hub.docker.com/layers/redimp/otterwiki/v2.0.0-beta26/images/sha256-02153d39385a9a1d9a3f4542844aac59ca52d020dd320d8e72d9dd927e5c9eb2?context=repo)

Another good find. Thank you @cueball23 !
