### ISSUE TITLE
Running into an issue with URI Linkning

### ISSUE THREAD

**Issue by a154james** [redimp/otterwiki#53]
I'm having an issue on my docker instance of the current version of OtterWiki, where the linked URI elements that are entered with header links, do not jump down the page when clicked. They also can't be auto scrolled to when using the #whatever at the end of the URL.

I can sort of cludge this to work by using a "#:~:text=" and then entering the text I'm trying to jump to, but that's a lot less elegant and doesn't fix the sidebar "on this page" links.

From the things I've tried, by forcing a div id/class on a section, it hasn't worked.

**Comment by redimp** [comment]
Please provide an example header that is not working. Use inspect on the `<a href"..">` that are generated for both the headers and the "On this page" links.

**Comment by a154james** [comment]
Sidebar:
<a href="#special-software" class="sidebar-link sidebar-toc-2">Special Software</a>
In line heading:
<a href="#in-house-software" class="anchor"><i class="fas fa-link"></i></a>

This is just one of the typical examples, but does the same for all internal doc links to specific headers on a page

**Comment by redimp** [comment]
Sorry, I've been blind. Bug confirmend and fixed in `2.0.0-beta27`.

`bleach` killed the `id` tags from the h[1234..] tags.
