### ISSUE TITLE
Mathjax/Latex without ticks

### ISSUE THREAD

**Issue by DuckieNukeEm** [redimp/otterwiki#57]
Within the code space, in order to execute latex code, two options are available:

1. Use inline tick marks IE \`$x=\frac{-b\pm \sqrt{b^2-4ac}}{sa}$\` to yield $x=\frac{-b\pm \sqrt{b^2-4ac}}{sa}$
2. Use the triple ticks with math extensions

\```math
`$x=\frac{-b\pm \sqrt{b^2-4ac}}{sa}$`
\```

for

```math
x=\frac{-b\pm \sqrt{b^2-4ac}}{sa}
```

However, other markdown setups can generate the above code without the singe or triple ticks marks. I was wondering, is it posible to have the Markdown logic expand to include latex without requiring tick marks?

**Comment by redimp** [comment]
I don't remember how I came up with the syntax ... will look into adding

1. `$\frac{1}{2}$` as inline MathJax
2. `$$\LaTeX$$` as block MathJax

to the renderer.

**Comment by redimp** [comment]
Implemented in 82dbfff (v2.0.0-beta37), see https://otterwiki.com/examples/MathJax for an example.
