### ISSUE TITLE
Nested nav menu

### ISSUE THREAD

**Issue by garymcnamara** [redimp/otterwiki#70]
It would be great to be able to navigate content via nested menus. 
Initially it can just be 'parent/child' directory, according to how the pages are created.

Long term, one solution could be:

When creating a new page, select it's parent page and sort order.
If no parent page is defined, the page is considered top of the directory tree
Sort order field is numerical only. Sort order starts from 1 (0 reserved for home / root, at very top if tree). Form input is validated to numerics only. No upper numerical value for sort order.
If no sort order is specified, enter a default value of 1
Nav bar sorts parent --> child relationships first numerically, then alphabetically

**Comment by redimp** [comment]
Hey @garymcnamara, thanks for the suggestion.

in https://github.com/redimp/otterwiki/discussions/60#discussioncomment-7804440 was discussed that the left sidebar could hold the page/directory tree. 

Does this match what you propose? (With the additional feature to have the option of putting an extra sorting to the elements)

**Comment by garymcnamara** [comment]
Thank you for your response.

Reading issue #60 - yes, that persons suggestion is exactly what I was thinking; nested menus like confluence. I would also suggest a mechanism to apply a custom sort order to pages within a subdirectory. Perhaps a config.md file in each directory containing the sort order.

________________________________

**Comment by redimp** [comment]
The nested Menu in the sidebar is in development. Preview:

![image](https://github.com/redimp/otterwiki/assets/112056/fa5a3fc2-5942-417d-9e17-7e1368e3c8d5)

**Comment by redimp** [comment]
Added in recent Release 2.1.0.
