### ISSUE TITLE
Make Pages available public or only for logged in Users

### ISSUE THREAD

**Issue by rcosg** [redimp/otterwiki#72]
It would be great to be able to set the Pages to public so anyone can access it or private so only logged in users can access it.

Example:
Public so i can send it to a customer: How to extend Disksize in vSphere
Private that only i need to know: How to set up SAN Storage and Switches

**Comment by redimp** [comment]
Thanks for opening this feature request. A similar request (for writing pages) can be found in #54. Let's discuss the matter there.
