### ISSUE TITLE
Increase the width of title on the index page

### ISSUE THREAD

**Issue by qwasfun** [redimp/otterwiki#80]
When writing articles using otterwiki, there are usually a few words in the title

On the index page, the space for the titles is too small now, they always wrap. 

Please increase the width of the titles

**Comment by redimp** [comment]
Thank you for this request. 

I've puzzeled a lot with the size of the tiles. Making each of them dynamic leads to pure chaos, when you have many pages with short names it looks like wasted space.

What is the width of your browser?
Whats the average length of your page names? 

Maybe a (blurred) screenshot is the best way to give me an idea of this problem.

**Comment by civviGH** [comment]
just fyi if you post a blurred image, depending on the blur algorithm it might not be destructive

**Comment by redimp** [comment]
I've played around with the container and the columns, this looks to me like something that might work for you:

Current Version:
![image](https://github.com/redimp/otterwiki/assets/112056/2db1aec8-2a7e-4dd4-b618-7a5f55686dd6)

Fixed Version:

![image](https://github.com/redimp/otterwiki/assets/112056/de880290-24de-4cad-9c80-3c8d091fe206)

What do you think?
