### ISSUE TITLE
[Feature Request] Default commit message.

### ISSUE THREAD

**Issue by kdirectorate** [redimp/otterwiki#81]
A way to specify a server default commit message, like the date and time, UUID, or just empty, would be nice. Most of my commits are "asdf" because we just aren't looking at or need the messages.

**Comment by redimp** [comment]
Thank you for this request. Will make it configurable that empty messages are allowed.

**Comment by redimp** [comment]
Available in [2.1.0.](https://github.com/redimp/otterwiki/releases/tag/v2.1.0).
