### ISSUE TITLE
Add 5-10 recent pages on the left hand side under "Index" and "create page" [FeatureRequest]

### ISSUE THREAD

**Issue by Balky79** [redimp/otterwiki#84]
Left hand side menu looks quite empty. 

Would it be possible to give it optional on/off for "recently changed" items or such, so you have recent links at your finger tips?

Or even Index of all pages there? Like on Confluence e.g.?

**Comment by redimp** [comment]
Thank you for requesting this feature. 

An extension of the sidebar is planned for the 2.1.0 Release, see #70.

**Comment by Balky79** [comment]
Ah, lovely! :)

**Comment by redimp** [comment]
Since [2.1.0](https://github.com/redimp/otterwiki/releases/tag/v2.1.0) the sidebar can be configured to display the Page Index. There is no mode yet for displaying the most recent files.
