### ISSUE TITLE
Page names case not reflected in filenames

### ISSUE THREAD

**Issue by weaversam8** [redimp/otterwiki#85]
Right now, page names are normalized to lowercase in Git and automatically raised to title case in the UI. The user should have the option to preserve case, so wikis written with other systems (that don't have all lowercase page names) can be imported seamlessly.

Related to #61.

**Comment by redimp** [comment]
In the filesystem all files are lowercase. Thats correct. Is this what is the issue that you are running into?

As mention in #61 an otter wiki can display other pagenames than just title: The upper- and lower-casing of the page names is decided by the first heading. For example a page with the title `# Mathjax` would be rendered as Mathjax, while `# MathJax` will be rendered as [MathJax](https://otterwiki.com/Examples/MathJax).

**Comment by redimp** [comment]
I've read this issue again. One question: Is the problem you are having importing markdown files from another wiki? If so, surely you have considered simply renaming the files. Does that not solve the problem?

**Comment by weaversam8** [comment]
Renaming the files would solve the problem, but may break other integrations with the wiki repo. One great thing about storing files in Markdown is that they can be used by different tools (e.g. a docs website generator.) Enforcing a particular naming scheme to use OtterWiki limits what types of Markdown repos OtterWiki can interact with.

I'm happy to do the work on this and make it configurable - are you open to a PR?

**Comment by redimp** [comment]
OK, I understand the problem. I never thought you could use the files for multiple purposes.

I put on my list to check if there is a nice way to make the page loading "fuzzy", as in check if the file exists with lowercase first. If that doesn't find a file, then see if it can find a file with the same name in any combination of upper and lower case.

A PR is very welcome. Please make sure all the tests pass, maybe add some ^^, and above all make sure you do not break backwards compatibility.

**Comment by ReessKennedy** [comment]
+1 - Just a vote that I think Otter could explode if it were built to work as a hub with some of the local markdown-based editors that are exploding right now, like Obsidian.

**Comment by weaversam8** [comment]
@redimp - PR opened. Let me know what you think.

**Comment by redimp** [comment]
Picked up the PR #88 and worked on it.

See [feature/retain-page-name-case](https://github.com/redimp/otterwiki/tree/feature/retain-page-name-case)

**Comment by redimp** [comment]
Feature released in [2.2.0](https://github.com/redimp/otterwiki/releases/tag/v2.2.0)

**Comment by Aitanuqui** [comment]
I'm using the latest tag, just to make sure, and I get a 404 error whenever I click on a page with upper case. I set `RETAIN_PAGE_NAME_CASE = True' as well.
