### ISSUE TITLE
The rename dialog should populate the folder name if a page is in a subfolder

### ISSUE THREAD

**Issue by weaversam8** [redimp/otterwiki#89]
Currently, renaming a page in a folder will not populate the folder name - if a page is in `folder/page-name.md`, the rename dialog will simply show `page-name`.

**Comment by weaversam8** [comment]
My mistake, this was fixed with the sidebar updates.

**Comment by redimp** [comment]
This has been fixed in 1570fd7 and I'm too slow :D
