### ISSUE TITLE
[feature] differntiate between read and write access for approved users

### ISSUE THREAD

**Issue by zmberber** [redimp/otterwiki#9]
it might be useful to have read only access for some users and read and write access for some other users.

currently, it is only possible to differentiate between users via being unregistered (anonymous user), registered, approved, and admin.  i want to have the wiki be hidden from public, i.e. not give read access to anonymous users, give all approved users read rights, and some users additionally write access.  currently, this is only possible by making the latter group of users admins.

it is not an option for me to make registered users have read access and approved users have write access, as anyone could instantly circumvent this by registering.  i want to manually approve who can see, and manually approve who can write.

currently, our setup is that we have http authentication (`.htpasswd`).

**Comment by guites** [comment]
This is also a feature that I would like to have. In addition to that, is there any way to allow users to edit content, but only publish it after approval of an admin? Thank you.

**Comment by redimp** [comment]
Thanks for the feedback, will bump the more advanced user permissions up my list.

Unfortunately will adding an approval system is way out of my scope. With git as data structure every change would be a pull request that an admin would have to merge. Sorry :/

**Comment by redimp** [comment]
added in 64ced5dbeb4277947f017de15119e7a6d73ac64b available in v2.0.0-beta38
