### ISSUE TITLE
Editor formatting buttons disappear on mobile

### ISSUE THREAD

**Issue by JD21P** [redimp/otterwiki#92]
Hi, the formatting buttons across the top in the editor are not accessible in a mobile browser in portrait mode, you have to rotate to landscape for them to appear.

Same when you shrink the PC web browser window too small.

Can a button be added to reveal these "Colapsed" buttons when the page size is reduced?

**Comment by JD21P** [comment]
Well, my post was from trying out the demo, but I've now transferred my home lab Docuwiki over to OtterWiki & loving it!

I haven't used markdown before but I easily remember most of the markdown symbols to not need the buttons, especially that the popup markdown help chart can be opened at the bottom of the editor window. :-D

A lot of the time, I'll lookup things on my mobile but never document them because Docuwiki is too clunky on mobile but OtterWiki works great.

One feature request would be, on the create new page screen, add a drop down box that contains a list of all current pages & subdirectories which can be selected to create a new subdirectory under, instead of having to write out "parentpage/subpage/subsubpage".

**Comment by redimp** [comment]
Will close this issue, but reconsider the toolbar for mobile editing while migrating to CodeMirror 5, see #105.

The requested feature for better creating nested pages has been discussed in #113 and has been released in [v2.4.3](https://github.com/redimp/otterwiki/releases/tag/v2.4.3).
